### PR TITLE
Fix Select Widget initialization value

### PR DESCRIPTION
**Pull request by teclator**
- It fixes the default value for new elements, and also respect the current value when editing.

### CODE REVIEW

**Comment by mvidner** [comment]
1. Overwriting the default sounds very wrong
2. I don't understand the problem: how can I reproduce the bug that this PR is fixing?

**Comment by teclator** [comment]
@mvidner  It works for you in all the cases?, try these scenarios with a `select` entry.

1. Edit an existent entry (pillar data)
2. Add a new element.

**Comment by teclator** [comment]
yast/form.yml

```yaml
---
team:
  $type: namespace
  name:
    $type: text
    $default: YaST
  members:
    $type: edit-group
    $prototype:
      $type: group
      name:
        "$type": text
      email:
        "$type": text
      location:
        "$default": Nuremberg
        "$type": select
        "$values":
          - Canary Islands
          - Nuremberg
          - Prague
    $default:
      - name: Knut
        email: kanderssen@suse.de
        location: Canary Islands
      - name: Martin Vidner
        email: mvidner@suse.com
        location: Prague
      - name: Imobach
        email: igonzalezsosa@suse.de
        location: Canary Islands
```

**Comment by teclator** [comment]
Closing it as @mvidner has a better approach

**Pull request closed without merging**
