### PR TITLE
Hash collections

### PR DESCRIPTION
**Pull request by imobachgs**
Support for hash-based collections.

### CODE REVIEW

**Comment by mvidner** [comment]
Trying to edit .root.bind.config.options results in an exception, probably because the value of the hash is a scalar string.

**Comment by mvidner** [comment]
Adding an item for the salftboot form still results in a UI error.

**Comment by imobachgs** [comment]
> Trying to edit .root.bind.config.options results in an exception, probably because the value of the hash is a scalar string.

Yes, that's it. I guess it should be rendered as a form with two elements (the `$key` which is the option name and the value). To start with, we should fix the `FormBuilder` class to handle this scenario.

However, I would rather prefer to fix this scenario in another PR.

**Comment by teclator** [comment]
> > Trying to edit .root.bind.config.options results in an exception, probably because the value of the hash is a scalar string.
> 
> Yes, that's it. I guess it should be rendered as a form with two elements (the `$key` which is the option name and the value). To start with, we should fix the `FormElementFactory` class to handle this scenario.
> 
> However, I would rather prefer to fix this scenario in another PR.

Fine with me

**Pull request merged**
